%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: /home/cgarcia/Documents/MATLAB/pqEDMDm/examples/Temperature/dyn_data.csv
%
% Auto-generated by MATLAB on 10-Apr-2024 08:33:50

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 5);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Time", "H1", "H2", "T1", "T2"];
opts.VariableTypes = ["double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data

dyndata = readtable(fileparts(mfilename("fullpath"))+"/dyn_data.csv", opts);


%% Clear temporary variables
clear opts